spring:
  application:
    name: bonusaccount
  liquibase:
    change-log: changelog/changelog-master.yml

  datasource:
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

consumer:
  client:
    topic: client.events
    group-id: client.events.bonus-account
    enabled: true
    threads: 1
    retry-count: 10
  card-event:
    topic: card.events
    group-id: card.events.bonus-account
    enabled: true
    threads: 1
    retry-count: 10
  payment-response:
    topic: payment.response
    group-id: payment.response.bonus-account
    enabled: true
    threads: 1
    retry-count: 10

producer:
  payment-request:
    topic: payment.request
    retry-count: 10

schedule:
  send-withdraw-request:
    cron: 0/5 * * * * *
